apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  selector:
    matchLabels:
      app: todo-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: okteto.dev/todo-backend:latest
        ports:
        - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8087
  selector:
    app: todo-backend